-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 17:57:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facility_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facility_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facility_management` DEFAULT CHARACTER SET utf8 ;
USE `facility_management` ;

-- -----------------------------------------------------
-- Table `facility_management`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facility_management`.`building` (
  `building_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NULL,
  `location` VARCHAR(100) NULL,
  PRIMARY KEY (`building_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facility_management`.`floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facility_management`.`floor` (
  `floor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `floor_number` INT NULL,
  `building_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`floor_id`),
  INDEX `fk_floor_building_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_floor_building`
    FOREIGN KEY (`building_id`)
    REFERENCES `facility_management`.`building` (`building_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facility_management`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facility_management`.`room` (
  `room_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(10) NOT NULL,
  `floor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_floor1_idx` (`floor_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_floor1`
    FOREIGN KEY (`floor_id`)
    REFERENCES `facility_management`.`floor` (`floor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facility_management`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facility_management`.`sensor` (
  `sensor_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('temperature', 'humidity', 'light', 'door') NULL,
  `int_value` INT NULL,
  `decimal_value` DECIMAL(14,4) NULL,
  `double_value` DOUBLE NULL,
  `string_value` VARCHAR(100) NULL,
  `boolean_value` BIT(1) NULL,
  `room_id` INT UNSIGNED NOT NULL,
  `unit` VARCHAR(50) NULL,
  PRIMARY KEY (`sensor_id`),
  INDEX `fk_sensor_room1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `facility_management`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
